### ISSUE TITLE
Calculating SHAs on new release branches

### ISSUE THREAD

**Issue by smallstepstoday** [nrwl/nx-orb#40]
## Orb version:

nrwl/nx@1.5.1

## What happened:

We use `master` branch commits to drive development builds. We create release branches (`release/0.0.x`) when we promote to staging/production. When CircleCI runs, the orb returns the _same SHAs_ for BASE/HEAD. As a result, the `affected` command yields no changes and no applications are built. This in turn requires that we create an additional commit which forces all the applications to rebuild.

## Expected behavior:

Ideally _all_ applications should be rebuilt when a new branch is created since there is no previous build on that branch.

## Additional Information:

Here is an example of the output from a pipeline based on a new release branch:
```
#!/bin/bash
echo "$PARAM_SCRIPT" >> "index.js"
RESPONSE=$(node index.js $CIRCLE_BUILD_URL $CIRCLE_BRANCH $PARAM_MAIN_BRANCH $PARAM_ERROR_ON_NO_SUCCESSFUL_WORKFLOW $PARAM_ALLOW_ON_HOLD $PARAM_WORKFLOW_NAME)
echo "$RESPONSE"
BASE_SHA=$(echo "$RESPONSE" | grep 'Commit:' | sed 's/.*Commit: //')
HEAD_SHA=$(git rev-parse HEAD)
echo "Base SHA"
echo $BASE_SHA
echo ""
echo "Head SHA"
echo $HEAD_SHA
echo ""
echo "export NX_BASE=\"$BASE_SHA\";" >> $BASH_ENV
echo "export NX_HEAD=\"$HEAD_SHA\";" >> $BASH_ENV
echo ""
echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"

Commit: 1a4e590311d1af213235f8c06de930675afab9e3
Base SHA
1a4e590311d1af213235f8c06de930675afab9e3

Head SHA
1a4e590311d1af213235f8c06de930675afab9e3


NX_BASE and NX_HEAD environment variables have been set for the current Job
CircleCI received exit code 0
```

Any assistance you can provide is much appreciated. Thanks!

**Comment by meeroslav** [comment]
Hi @smallstepstoday, sorry for the super late reply.

Do you have a separate workflow defined from your release branches or do you use the same? Based on the output log I suspect your first run ended up on the line: https://github.com/nrwl/nx-orb/blob/main/src/scripts/find-successful-workflow.js#L19

The base SHA will always be calculated as `git merge-base origin/master HEAD` which in this case is the same as your starting commit in the release branch. I believe this is correct behavior since nothing changed between master and release so there's nothing to run.

I would suggest to create another workflow that is only triggered on the branch creation which runs `nx run-many --all --target=...` instead of `nx affected...`.

**Comment by meeroslav** [comment]
Closing due to staleness
